; COMENZAR EN LA POSICION DE MEMORIA F000
.ORG F000H
; DIVIDIR 224 ENTRE 2
; CARGAR BC CON 224D
MVI C, E0H
; MOVER C AL ACOMULADOR
MOV A,C
; ROTAR A LA DERECHA LOS BITS
RAR
; MOVER EL ACMULADOR AL REGISTRO C
MOV C,A

HLT
