.ORG f000h	;INICIAR EN F000
LXI H, 0EH	;EL DIVIDENDO EN LA PAREJA HL
MVI B, 04H	;EL DIVISOR ALMACENAR EN B
MVI C, 08	;INCIAR EL CONTADOR DESDE 08
UP: DAD H	;DESPL. 1 BIT HACIA LA IZQUIERDA CON: HL = HL + HL
MOV A, H	;CARGAR H EN A
SUB B		;REALIZAR A = A - B
JC DOWN	;SI B >! A IR AL LBL: DOWN  
MOV H,A	;CARGAR H EN A
INR L		;INCREMENTAR L
DOWN: DCR C	;DECREMENTAR EL CONTADOR POR 1
JNZ UP	;SI NO ES CERO REGRESAR AL LBL: UP
SHLD 8020H	;ALMACENAR EL RESULTADO DE H Y L EN LA DIR. 8020
HLT		;TERMINAR EL PROGRAMA